spring:
  application:
    name: hello-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:1111/eureka/
#      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
