
server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
spring:
  application:
    name: feign-consumer

HELLO-SERVICE:
  ribbon:
    ConnectTimeout: 500
    ReadTime: 2000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1

